### ISSUE TITLE
Better ban appeal handling

### ISSUE THREAD

**Issue by 0xallie** [palera1n/bot-rewrite#39]
Instead of the current Google form solution which is prone to spam, mistakes and false appeals on behalf of others, I imagine a solution like this:

## High priority
- Users are linked directly to the appeals server when they are banned.
- In the main channel (`#overview`) there should be a message from the bot with a "Submit Appeal" button, which double-checks that the user is banned (even though the bot should kick them if they're not anyway), and presents a form to submit their appeal reason.

## Medium priority
- For appeals beyond the first one, it should enforce a 3 month delay from the previous appeal. On the first appeal, this need not be enforced, but there should be a warning somewhere stating that it is recommended to wait 3 months before appealing in most cases, as not doing so may reduce your chances of success and number of allowed appeals.
- If the user has already appealed 3 times, any further appeals should be automatically denied.

## Low priority
- Have a "Close Appeal" button usable by administrators only that closes and locks the thread, DMs the user about the result of their appeal (sending a notice to the closing admin if DMing failed), and perhaps even automatically unbans if the appeal was accepted.

**Comment by JanCraft** [comment]
Bot cannot DM users after they're banned. Either we make our own /ban wrapper that DMs first and then bans, or we have to find another way to DM the invite link.

**Comment by JanCraft** [comment]
Pythonplayer suggested we send the DM with the invite upon joining the main server, that way once you're banned you have the link in DMs. Will be doing that.

**Comment by justtryingthingsout** [comment]
A user having reached the server limit will not be able to join an appeals server, and extending onto that, the current system of simply banning users makes it so that a user that has exceeded the server limit through Nitro, then loses nitro and gets banned will have to leave however many servers it takes to reach 99 servers to then join the appeals server or even the main server.  The easiest solution for a user faced with this problem will therefore just make an alt account and try to join either the main or the appeals server, which would most likely end in a misunderstanding leading to a perma ban with no appeal. 

My proposal would be to never ban the user using Discord's ban at all, instead simply assigning a 'banned' role to the user or stripping all roles from a user, which should result in being able to see an info channel, which should consist of either
* A server invite to the appeals server (problematic due to the reasons described above but will fix having to DM every member joining)
* A ban reason, and an appeals system (such as a ticketing system that makes a discussion channel/thread) right in the main server itself, removing the need for any external appeals server.

**Comment by samiiau** [comment]
The appeal server was always optional to join to know if you're unbanned or staying banned, you're not required to join in the slightest but you're still able to make an appeal for the mods to review.

This system is a bad idea.

**Comment by 0xallie** [comment]
@JanCraft I know bots can't DM *after* banned, the current bot DMs before banning because of this. Do we not have a `/ban` command in Bridget yet? I guess that makes sense if we're going to support native features, though the native `/ban` command is a little annoying by forcing you to specify how many messages to delete anyway.

@justtryingthingsout Yeah, sure, there can be cases where people reach the server limit, though it's usually not an issue as being banned from the palera1n server frees up a slot for the appeals server. The case you mention of happening to lose Nitro at and having to leave a lot of servers is probably a rare edge case, and I'd say "too bad". The system you propose feels overly complicated for little benefit and causes new issues:
* It makes alting much easier, as they are no longer subject to the IP ban they normally are when they get banned.
* It allows them to continue to DM and harass server members through the mutual server. This could only really be mitigated somewhat by hiding even the general info channels from them and only showing an appeal channel that's not visible to regular members, but it sucks to have to hide the info channels from them and this only makes it harder for them to find members to harass in the member list, it doesn't make it impossible to DM the non-visible members as far as I know.

@samiiau Okay, but how else do you propose to stop troll appeals? It's simply not possible with the current Google form solution. If we validate the username and/or ID and check if they're actually banned, it may miss legitimate appeals and still won't stop trolls from using the details of an actual banned user to submit troll appeals.

The only alternative to my proposal I can think of that would prevent troll appeals is having a website with Discord OAuth login to authenticate your account.

**Comment by JanCraft** [comment]
Bridget uses native discord moderation buttons, so idea was never doing our own /ban.
I agree with the idea that the server limit is a rare edge case.

Discord OAuth is a possibility, it's just that making the website is gonna take its time. Then again that solves the no DM problem since users just go to https://palera.in/appeal.

**Comment by junepark678** [comment]
@0xallie currently the `/ban` command in GIRRewrite-based bots only support deleting with a fixed timeout. I wanted to use the built-in `/ban` command in Discord as it gives more flexibility. Also, with using native modactions, Discord's built-in Audit Log system becomes more relevant. 

P.S. I wish there was a way to add custom Audit Log entries.

**Comment by 0xallie** [comment]
Yeah, being able to specify at least whether to delete messages is a good thing, though it's a bit annoying to be forced to choose IMO. But on second thought maybe it's a good idea to require it on a bigger server like palera1n. 

For the majority of cases "don't delete any" and "delete past 24 hours of messages" is probably good enough, the second one being used in case of spam or other bad messages that need to be cleaned, though it could be overshooting in case, e.g. in case of a normally somewhat well-behaved member, so it doesn't hurt to have more options too.

As for the audit log, isn't the only issue that it says banned by the bot? It could probably append the username of the moderator who banned the user to the audit log reason, though it is a bit nicer if you immediately see who banned at a glance.
